### PR TITLE
add background fetch and local notification for world

### PR DESCRIPTION
**Pull request by pbeo**
plans to add the ability to track several regions in the future

### CODE REVIEW

**Comment by pbeo** [comment]
plans to add the ability to track several regions in the future

**Comment by mhdhejazi** [comment]
Thank you for your contribution, Piotr!

The idea is cool, but I can't help but ask how could this be useful in the real world? I mean the data is being updated all the time, and close to real-time sometimes. So we need to ask ourselves, what's the added value of a notification that pops up after 5 minutes from leaving the app to tell the user that the stats have changed to X?
Will the user find such notifications really useful or annoying?

I think notifications work best when there is some event that we're waiting for but don't know when exactly it might happen (think of live games, breaking news, ..etc). But for things that change all the time (like the temperature, stock prices, or the stats here) notifications don't make a lot of sense, and could be very annoying to the users.

**Comment by FluffyDev2019** [comment]
1. I maby can answer that somewhat...
For ex Sweden, the updates does "only" come once a day, and for perfect function, even if there several I would like to have the option to get notifications in regards to changes.

2. Maby also get to choose World + other countries to see simultaneously on as widget, as a extended widget.

3. This kind of graph is most wanted in Corona Tracker to be able to see and compare choosen counties against each other for ex Deaths. (see attached picture)

0DEF898A-A774-4ADA-B9E6-5667060123CE


Regards

**Comment by mhdhejazi** [comment]
So, after some thought, I think we can make this a bit better.

1. For the countries where the data is updated more frequently, we can schedule the background fetch every one or two hours. This will reduce the number of notifications and make them less annoying.

2. It's not a good idea to immediately ask the user to allow us to send notifications without a proper context. I think we should only do that after the user "subscribes" to the notifications. This leads us to the UI design, and here I suggest adding an item to the main menu called "Subscribe", perhaps with a bell icon, which the user can tap to subscribe to the updates of the selected location. Only at that time we'll ask for their permission.

3. `DataManager.download()` is an overkill for this feature as it downloads 3 time-series files that we don't need. I think it's enough to call `JHUWebDataService.instance.fetchReports`, or add `onlyReports` parameter to `DataManager.download()` with a default value of `false`, and pass `true` when we call it here.

4. [Optional] We should consider using custom design for the notification to present the numbers in a nicer way. To achieve this we can use [notification content app extension](https://developer.apple.com/documentation/usernotificationsui/customizing_the_appearance_of_notifications).

Please feel free to post any questions here while you're working on this. I'll try to be as responsive as possible.

**Comment by mhdhejazi** [comment]
> 1. For ex Sweden, the updates does "only" come once a day

Yeah, it makes sense in this case since it's a one-time notification.

> 2. Maby also get to choose World + other countries to see simultaneously on as widget, as a extended widget.

Piotr started working on something similar in a [separate branch](https://github.com/mhdhejazi/CoronaTracker/tree/feature/widget-favorites), but I found out it'll make things more complicated for users as they may need to manually configure a shared group between the app and the widget extension which isn't intuitive for regular users.

For 3. and any other requests, I'd appreciate it if you create separate issues for them and keep this discussion focused on notifications. Thanks!

**Comment by mhdhejazi** [comment]
Are you still interested in doing this feature Piotr?

**Comment by mhdhejazi** [comment]
I realized I didn't mention you @pbeo

**Comment by mhdhejazi** [comment]
Closing due to inactivity.

**Pull request closed without merging**
