### PR TITLE
Added Romanian (ro-RO) translation

### PR DESCRIPTION
**Pull request by rhcpfan**
Thank you for your hard work! Stay safe 👍

### CODE REVIEW

**Comment by MhdHejazi** [comment]
Thank you for your contribution!

Actually, only `Localizable.strings` file should be translated, the strings in the storyboards are just placeholders.

Sorry for not making this clear enough.

**Comment by rhcpfan** [comment]
Glad I could help!

I have translated "Main.strings" mainly because of the text that says where the data is from (`Data: The Center for Systems Science and Engineering at Johns Hopkins`).

And also thought that the widget might use translation also 😄

Let me know if you'd like me to remove the files.

**Comment by ppamorim** [comment]
@rhcpfan That's a problem in the storyboard since it's not localized...

**Comment by ppamorim** [comment]
@rhcpfan You are correct.

**Comment by MhdHejazi** [comment]
> So the idea is that every string that can be translated should be in `Localizable.strings`? For static texts that are declared in IB, I've always used that storyboard's `.strings` file...

Yes. I prefer keeping the strings in one file and reuse them everywhere. You can also choose a better name for strings than "sRc-qE-tlW".

> Let me know if you'd like me to remove the files.
Yes, remove them please.

**Comment by rhcpfan** [comment]
I have removed the above mentioned .strings files and added the data format (`"Data: %1$@"`) and the JHU data provider (`"The Center for Systems Science and Engineering at Johns Hopkins"`) in `Localizable.strings`. Let me know if there's anything else to be done. Thank you again for your awesome work! 👍

**Comment by MhdHejazi** [comment]
Thanks for adding an entry for the data source. I didn't actually forget about it but thought it's not important since I prefer to keep the source name without translation. But yes, we can translate "Data:" or maybe "Source:".

I'd prefer to keep this PR for translating the existing strings, but you can keep the `Data:` entry in the Romanian file. Changing other files caused conflicts so please keep the changes to the Romanian file.

**Comment by mhdhejazi** [comment]
If you need any help with this please let me know.

**Comment by mhdhejazi** [comment]
I added the translation file manually as this PR can't be merged.

Thank you again for your contribution.

**Pull request closed without merging**
