### PR TITLE
Feature/favorite

### PR DESCRIPTION
**Pull request by pbeo**
- Added favorite region button in app
- Added favorite region in today extension

### CODE REVIEW

**Comment by MhdHejazi** [comment]
Thanks for this addition!

A couple of points:
1. I've added a menu to the bottom panel to declutter the header. So, no need to add/change anything in the storyboard. You can add the favorite button under the menu, and use a title like "Show in widget". This also makes the purpose of the button clearer.
2. I think it's better to use a star shape instead of a heart shape.
3. I used tabs for indentation, so please keep the tabs and don't use spaces in your code.
4. Make sure not to commit developer-specific changes (like the team id). Only commit the changes that contribute to the feature you added.

Thank you again!

**Comment by pbeo** [comment]
> Thanks for this addition!
> 
> A couple of points:
> 
> 1. I've added a menu to the bottom panel to declutter the header. So, no need to add/change anything in the storyboard. You can add the favorite button under the menu, and use a title like "Show in widget". This also makes the purpose of the button clearer.
> 2. I think it's better to use a star shape instead of a heart shape.
> 3. I used tabs for indentation, so please keep the tabs and don't use spaces in your code.
> 4. Make sure not to commit developer-specific changes (like the team id). Only commit the changes that contribute to the feature you added.
> 
> Thank you again!

Hmmm it's strange. I use Swimat for code formatting, I will check that

**Comment by pbeo** [comment]
Please check right now

**Comment by MhdHejazi** [comment]
Merged to feature/widget-favorites branch. Thanks for your contribution!

**Comment by MhdHejazi** [comment]
I ran into a problem with registering the widget app id, it says the app id is used by another team (It could be that you or somebody else registered this app id by mistake).
image

Sharing the data between the app and the widget requires a non-wildcard app id that also has the "App Groups" capability enabled. This means anyone will try to use the app now will need to change the app id of the app and widget for Xcode to create the needed profiles. Currently, nothing special is needed before running the app because Xcode can use the wildcard app id every developer has.

Because of that, I'm leaving this branch and not merging back into the master for now.

**Pull request merged**
