### PR TITLE
Swiftlint

### PR DESCRIPTION
**Pull request by ppamorim**
Massive changes here done mostly automatically by Swiftlint. This fix some Swift issues and code alignment.

### CODE REVIEW

**Comment by MhdHejazi** [comment]
Yeah, a lot of changes here. But I'd rather review the most important issues and fix them manually, and not use the auto mode.

Thanks for bringing this to my attention!

**Comment by ppamorim** [comment]
I disagree with your point. Swiftlint does a very good job by fixing some basic mistakes done in this project and helps to keep your project consistent when a PR is merged. I wasted hours yesterday fixing the project and using the correct Swift syntax. Without a correct base you will be unable to keep a standard in your project.

**Comment by MhdHejazi** [comment]
I have no problem with SwiftLint and will integrate it later. It's just not the top priority now.

I didn't merge this PR for the reasons I mentioned before, and because improving such a big PR needs much discussion and time. So, I'd rather do the most important changes manually as I've told you.

Sorry about that, and thanks for your contribution.

**Comment by ppamorim** [comment]
@MhdHejazi Why not keep the PR open so?

**Pull request closed without merging**
